PEOPLE = [
    "Albert Einstein",
    "Marie Curie",
    "Leonardo da Vinci",
    "William Shakespeare",
    "Ada Lovelace",
    "Nikola Tesla",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Taylor Swift",
    "Frida Kahlo",
    "Napoleon Bonaparte",
    "Cleopatra",
    "Isaac Newton",
    "Charles Darwin",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Stephen Hawking",
    "Vincent van Gogh",
    "Ludwig van Beethoven",
    "Abraham Lincoln",
]

PLACES = [
    "Eiffel Tower",
    "Great Wall of China",
    "Taj Mahal",
    "Grand Canyon",
    "Machu Picchu",
    "Colosseum",
    "Hagia Sophia",
    "Statue of Liberty",
    "Pyramids of Giza",
    "Mount Everest",
    "Stonehenge",
    "Angkor Wat",
    "Petra",
    "Niagara Falls",
    "Amazon River",
    "Sahara Desert",
    "Venice",
    "Acropolis of Athens",
    "Chichen Itza",
    "Santorini",
]
